selected_scheme scheme-minimal
TEXDIR ./texlive
TEXMFCONFIG ~/.texlive2018/texmf-config
TEXMFHOME ~/texmf
TEXMFLOCAL ./texlive/texmf-local
TEXMFSYSCONFIG ./texlive/texmf-config
TEXMFSYSVAR ./texlive/texmf-var
TEXMFVAR ~/.texlive2018/texmf-var
portable 1