name: Compile and Upload LaTeX Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Install LaTeX packages
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive texlive-xetex texlive-fonts-recommended texlive-fonts-extra

    - name: Compile LaTeX files
      run: |
        find . -type f -name '*.tex' -exec pdflatex {} \;

    - name: Upload compiled PDF files
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdfs
        path: |
          |
          $(find . -type f -name '*.pdf')

